//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricUserCourse
    {
        public int RegistrationID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime DateArrival { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
