//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfInterest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int OrderPOI { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TypePOIID { get; set; }
        public Nullable<int> PositionID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Position Position { get; set; }
        public virtual TypePOI TypePOI { get; set; }
    }
}
