//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public int ApplicationUserID { get; set; }
        public int CourseID { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Course Course { get; set; }
        public virtual HistoricUserCourse HistoricUserCourse { get; set; }
    }
}
